<body>
<script>
// Promise.any takes array of promises and waits for first success and return the result of the promise.
// if all promises are rejected then it will return the array of errors 



const p1 = new Promise((resolve, reject) => {
  setTimeout(() => resolve("P1 success"), 3000);
})

const p2 = new Promise((resolve, reject) => {
  setTimeout(() => resolve("P2 success"), 1000);
})

const p3 = new Promise((resolve, reject) => {
  setTimeout(() => resolve("P3 success"), 2000);
})

const p4 = new Promise((resolve, reject) => {
  setTimeout(() => reject("P4 fail"), 2000);
})

const p5 = new Promise((resolve, reject) => {
  setTimeout(() => reject("P5 fail"), 2000);
})

Promise.any([p1, p2, p3, p4])
.then(res => {
  console.log(res)
})
.catch(err => {
  console.error(err)
})
// P2 success

Promise.any([p4, p5])
.then(res => {
  console.log(res)
})
.catch(err => {
  console.error(err)
  console.log(err.errors)
})
// AggregateError: No Promise in Promise.any was resolved
// Array [ "P4 fail", "P5 fail" ]

</script>
</body>